### PR TITLE
fix gemspec version

### PR DESCRIPTION
**Pull request by dai-vdr**
T/O

### CODE REVIEW

**Comment by banister** [comment]
Thansk,

But is it possible to just require the version inside the gemspec and use that instead?

We do something like that here: https://github.com/pry/pry/blob/master/pry.gemspec#L2-L6

However when i do that in `method_source` i notice that i end up with constant redefinition warnings when running pry in `method_source`. Would you be able to figure out what's going on here? 👍

**Comment by dai-vdr** [comment]
Your approach is better than mine.
But i did not get constant redefinition warnings with running pry...

**Comment by banister** [comment]
@dai-vdr turns out we have a rake task that does this automatically: `rake gemspec` so i just ran that and then committed it

**Comment by dai-vdr** [comment]
thanks! 👍

**Pull request closed without merging**
